name: Deploy to Cloudflare Pages
on: [push]
jobs:
  Build and Deploy:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    env:
      CLOUDFLARE_API_TOKEN: ${{secrets.CF_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - name: Install
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: "npm"
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: |
          npm install -g wrangler
          wrangler pages publish ./public --project-name ${{github.action_repository}} --commit-hash ${{env.GITHUB_SHA}}
      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Deploy to Cloudflare Pages
          conclusion: ${{ job.status }}
          output: |
            {"summary":${{ steps.test.outputs.summary }}}
