name: Deploy to Cloudflare Pages
on: [push]
jobs:
  Build and Deploy:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    env:
      CLOUDFLARE_API_TOKEN: ${{secrets.CF_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - name: Install
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: "npm"
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: |
          npm install -g wrangler
          wrangler pages publish ./public --project-name ${{github.action_repository}} --commit-hash ${{env.GITHUB_SHA}}
      - name: Check - Success
        if: ${{success()}}
        run: curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}"\
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{github.repository}}/check-runs \
              -d '{"name":"deploy to Cloudflare Pages","head_sha":"${{GITHUB_SHA}}","status":"complete","external_id":"${{job.container.id}}","conclusion":"success"'
      - name: Check - Failure
        if: ${{failure()}}
        run: curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}"\
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{github.repository}}/check-runs \
              -d '{"name":"deploy to Cloudflare Pages","head_sha":"${{GITHUB_SHA}}","status":"complete","external_id":"${{job.container.id}}","conclusion":"failure"'
      